import gql from "graphql-tag";
//import Lesson from "../fragments/lessonWithVariants"

export default gql`
  query getTutorBatches($shopId:ID, $tutorId:ID ) {
    getTutorBatches(shopId:$shopId, tutorId:$tutorId){
      _id
      name
      shopId
      programId
      createdBy
      createdAt
      batchStartTime
      batchEndTime
      startDate
      batch_max_limit
      mode
      availableDays
      seatsFilled
      seatsAvailable
      students{
        _id
        emailRecords{
            address
            verified
        }
        profile{
            isStatus
            isApproved
            availableDays
            certificates
            address
            picture
            price
            qualification
            categories
            experience
            bio
            selectedToTime
            selectedFromTime
        }
        userMedia {
          _id
          URLs {
            thumbnail
          }
          priority
        }
        role
        userId
        isProfile
        name
        phoneNumber
      }
      tutors{
        _id
        emailRecords{
            address
            verified
        }
        profile{
            isStatus
            isApproved
            availableDays
            certificates
            address
            picture
            price
            qualification
            categories
            experience
            bio
            selectedToTime
            selectedFromTime
        }
        userMedia {
          _id
          URLs {
            thumbnail
          }
          priority
        }
        role
        userId
        isProfile
        name
        phoneNumber
      }
      admins{
        _id
        emailRecords{
            address
            verified
        } 
        profile{
            isStatus
            isApproved
            availableDays
            certificates
            address
            picture
            price
            qualification
            categories
            experience
            bio
            selectedToTime
            selectedFromTime
        }
        userMedia {
          _id
          URLs {
            thumbnail
          }
          priority
        }
        role
        userId
        isProfile
        name
        phoneNumber
      }
      program{
              _id
              type
              name
              field
              createdAt
              createdBy
              price
              program_content
              isApproved
              duration
              account{
                _id
                name
              }
              batches {
                _id
                name
                batchStartTime
                batchEndTime
               
              }
              programMedia {
                _id
                URLs {
                  small
                  medium
                  large
                  thumbnail
                }
                priority
              }
              products{
                _id
                title
                tutors{
                  _id
                  emailRecords{
                      address
                      verified
                  }
                  profile{
                      isStatus
                      isApproved
                      availableDays
                      certificates
                      address
                      picture
                      price
                      qualification
                      categories
                      experience
                      bio
                      selectedToTime
                      selectedFromTime
                  }
                  userMedia {
                    _id
                    URLs {
                      thumbnail
                    }
                    priority
                  }
                  role
                  userId
                  isProfile
                  name
                  phoneNumber
                }
                lessonsDuration {
                  lesson{
                    _id
                    name
                    topics{
                      _id
                      topic_name
                      topic_content
                      createdAt
                    }
                    assignments{
                      _id
                      assignment_title
                      createdAt
                      createdBy
                    }
                    quizs{
                      _id
                    }
                  }
                  lessonDuration
                }
              }
              }
      lessonsDuration{
        lesson{
          _id
          name
          product{
            title
            _id
            tutors{
              _id
              emailRecords{
                  address
                  verified
              }
              profile{
                  isStatus
                  isApproved
                  availableDays
                  certificates
                  address
                  picture
                  price
                  qualification
                  categories
                  experience
                  bio
                  selectedToTime
                  selectedFromTime
              }
              userMedia {
                _id
                URLs {
                  thumbnail
                }
                priority
              }
              role
              userId
              isProfile
              name
              phoneNumber
            }
          }
          topics{
            _id
            topic_name
          }
          assignments{
            _id
            assignment_title
          }
          quizs{
            _id
            quiz_title
          }
        }
        lessonDuration
        lessonStatus
        lessonScheduleDate
        meetingInfo{
          meetingDate
          link
          recordedLink
          platform
        }
        tutor{
          _id
          emailRecords{
            address
            verified
          }
          profile{
            isStatus
            isApproved
            availableDays
            certificates
            address
            picture
            price
            qualification
            categories
            experience
            bio
            selectedToTime
            selectedFromTime
          }
          userMedia {
            _id
            URLs {
              thumbnail
            }
            priority
          }
          role
          userId
          isProfile
          name
          phoneNumber   
        }
      }
    }
  }

`;