import gql from "graphql-tag";

export default gql`
query getStudentEnroleProgramsBatches($query:String) {
  getStudentEnroleProgramsBatches(query:$query) {
    _id
    name
    shopId
    programId
    createdBy
    createdAt
    batchStartTime
    batchEndTime
    isCourseComplete
    certificate{
      _id
      templateImage
      template
      logo
      certifiTemp
      authority{
        designation
        name
        sign
      }
    }
    isPayment
    mode
    availableDays
    startDate
    endDate
    tutors{
      _id
      emailRecords{
          address
          verified
      }
      userMedia {
        _id
        URLs {
          thumbnail
        }
        priority
      }
      role
      userId
      isProfile
      name
      phoneNumber
    }
    program{
      _id
      type
      name
      createdAt
      createdBy
      price
      isPublished
      isApproved
      duration
      batches {
        _id
        name
        batchStartTime
        batchEndTime
        batch_max_limit
        seatsFilled
        seatsAvailable
        startDate
      }
      faqs {
        faqType
        qAndA{
          question
          answer
        }
      }
      program_content
      account{
        _id
        name
      }
      programMedia {
        _id
        URLs {
          small
          medium
          large
          thumbnail
        }
        priority
      }
      tutors{
        _id
        name
        userMedia {
          _id
          URLs {
            thumbnail
          }
          priority
        }
      }
      products{
        _id
        title
        tutors{
          _id
          emailRecords{
              address
              verified
          }
          profile{
            isStatus
            isApproved
            availableDays
            certificates
            address
            picture
            price
            qualification
            categories
            experience
            bio
            selectedToTime
            selectedFromTime
          }
          userMedia {
            _id
            URLs {
              thumbnail
            }
            priority
          }
          role
          userId
          isProfile
          name
          phoneNumber
        }
        lessonsDuration {
          lesson{
            _id
            name
            topics{
              _id
              topic_name
              topic_content
              createdAt
            }
            assignments{
              _id
              assignment_title
              createdAt
              createdBy
            }
            quizs{
              _id
              quiz_question
              quiz_answer
              quiz_hint
              quiz_options{
                optionA
                optionB
                optionC
                optionD
              }
            }
          }
          lessonDuration
          lessonStatus
        }
      }
    }
    lessonsDuration{
      lesson{
        _id
        name
        product{
          title
          _id
          tutors{
            _id
            emailRecords{
              address
              verified
            }
            profile{
              isStatus
              isApproved
              availableDays
              certificates
              address
              picture
              price
              qualification
              categories
              experience
              bio
              selectedToTime
              selectedFromTime
            }
            userMedia {
              _id
              URLs {
                thumbnail
              }
              priority
            }
            role
            userId
            isProfile
            name
            phoneNumber
          }
        }
        topics{
          _id
          topic_name
        }
        assignments{
          _id
          assignment_title
        }
        quizs{
          _id
          quiz_title
        }
      }
      lessonDuration
      lessonStatus
      lessonScheduleDate
      meetingInfo{
        meetingDate
        link
        recordedLink
        platform
      }
      tutor{
        _id
        emailRecords{
          address
          verified
        }
        profile{
          isStatus
          isApproved
          availableDays
          certificates
          address
          picture
          price
          qualification
          categories
          experience
          bio
          selectedToTime
          selectedFromTime
        }
        userMedia {
          _id
          URLs {
            thumbnail
          }
          priority
        }
        role
        userId
        isProfile
        name
        phoneNumber   
      }
    }
  }
}
`;
